apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-deployment
  labels:
    app: cats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats
  template:
    metadata:
      labels:
        app: cats
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: cats
        image: natereid/cats:v.0.0.2
        ports:
        - containerPort: 5000
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true