apiVersion: v1
kind: Service
metadata:
  labels:
    app: cats
    app.kubernetes.io/instance: random-cats
  name: cats-deployment
  namespace: cats-app
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: cats
  type: ClusterIP
